
-- add token que o gateway retorna ao realizar a transacao
ALTER TABLE `PAG01_TRANSACAO` ADD `TOKEN_GATEWAY` VARCHAR(200) NULL AFTER `TRANSACAO_DT_CADASTRO`, ADD INDEX (`TOKEN_GATEWAY`);

-- add forma de pagamento no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_FORMA_PAG` VARCHAR(50) NULL DEFAULT NULL AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_FORMA_PAG`);

-- add o gateway escolhido no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_GATEWAY` VARCHAR(50) NOT NULL DEFAULT 'pagseguro' AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_GATEWAY`);
