
-- add token que o gateway retorna ao realizar a transacao
ALTER TABLE `PAG01_TRANSACAO` ADD `TOKEN_GATEWAY` VARCHAR(200) NULL AFTER `TRANSACAO_DT_CADASTRO`, ADD INDEX (`TOKEN_GATEWAY`);

-- add forma de pagamento no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_FORMA_PAG` VARCHAR(50) NULL DEFAULT NULL AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_FORMA_PAG`);

-- add o gateway escolhido no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_GATEWAY` VARCHAR(50) NOT NULL DEFAULT 'pagseguro' AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_GATEWAY`);

-- permite produto null - para o caso de venda avulsa
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` CHANGE `LOJ12_PRODUTO_ID` `LOJ12_PRODUTO_ID` INT(11) NULL; 

-- novos campos do pedido
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` ADD `LOJ12_NOME_PRODUTO` VARCHAR(100) NOT NULL AFTER `LOJ12_PEDIDO_ID`, ADD `LOJ12_QTD` INT NOT NULL AFTER `LOJ12_NOME_PRODUTO`, ADD `LOJ12_VLR_UNID` DECIMAL(10,2) NOT NULL AFTER `LOJ12_QTD`, ADD `LOJ12_ID_VARIACAO` INT NOT NULL AFTER `LOJ12_VLR_UNID`;

-- exclusao do campo stats da tabela LOJ12_PRODUTO_PEDIDO 
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` DROP `LOJ12_STATS`;

-- a variação passa a ficar no pedido, ou seja um pedido tem uma variacao
DROP TABLE `LOJ13_PRODUTO_PEDIDO_VARIACAO`;

-- novo index para relacionamento
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` ADD INDEX(`LOJ12_ID_VARIACAO`);

-- correção de tipo de campo
ALTER TABLE `LOJ07_LOJA` CHANGE `LOJ07_NOME` `LOJ07_NOME` VARCHAR(100) NOT NULL;
ALTER TABLE `LOJ09_VARIACAO_PRODUTO` CHANGE `LOJ09_GRUPO` `LOJ09_GRUPO` VARCHAR(50) NOT NULL;

-- o usuário (quem compra) pode nao ser cadastrado no sistema
ALTER TABLE `LOJ11_PEDIDO` CHANGE `LOJ11_USUARIO_ID` `LOJ11_USUARIO_ID` INT(11) NULL;

-- campo para identificar a hash do pagseguro da loja
ALTER TABLE `LOJ07_LOJA` ADD `LOJ07_HASH_PAGSEGURO` VARCHAR(100) NOT NULL AFTER `LOJ07_EMAIL`, ADD INDEX (`LOJ07_HASH_PAGSEGURO`);

-- novos campos da loja para configuração da mesma
ALTER TABLE `LOJ07_LOJA` ADD `LOJ07_CARTAO_MAX_PARC` INT(2) NULL DEFAULT NULL COMMENT 'Se NULL não aceita cartão' AFTER `LOJ07_HASH_PAGSEGURO`, ADD `LOJ07_FLG_BOLETO` TINYINT(1) NOT NULL DEFAULT '1' AFTER `LOJ07_CARTAO_MAX_PARC`, ADD `LOJ07_FRETE` DECIMAL(10,2) NOT NULL DEFAULT '0' AFTER `LOJ07_FLG_BOLETO`;

-- novo campo na loja para o nick do instagram
ALTER TABLE `LOJ07_LOJA` ADD `LOJ07_NICK_INSTAGRAM` VARCHAR(50) NOT NULL AFTER `LOJ07_EMAIL`;

-- correção no nome do campo
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` CHANGE `LOJ12_ID_VARIACAO` `LOJ12_VARIACAO_ID` INT(11) NOT NULL;

-- correção: troca do ID do cliente pelo ID da loja (o pedido é da loja) + relações de chave estrangeira (FK)
ALTER TABLE `LOJ11_PEDIDO` CHANGE `LOJ11_CLIENTE_ID` `LOJ11_LOJA_ID` INT(11) NOT NULL;
ALTER TABLE `LOJ11_PEDIDO` ADD CONSTRAINT `LOJ11_PEDIDO_ibfk_1` FOREIGN KEY (`LOJ11_LOJA_ID`) REFERENCES `minhaloja`.`LOJ07_LOJA`(`LOJ07_ID`) ON DELETE RESTRICT ON UPDATE NO ACTION;

-- registra o frete no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_FRETE` DECIMAL(10,2) NULL DEFAULT NULL AFTER `LOJ11_VALOR`;

-- view do produto alterado para like(opção "gostei" no produto)
ALTER TABLE `LOJ08_PRODUTO` CHANGE `LOJ08_QTD_VIEW` `LOJ08_QTD_LIKE` INT(11) NOT NULL DEFAULT '0';

-- tamanho da logo maior
ALTER TABLE `LOJ07_LOJA` CHANGE `LOJ07_LOGO` `LOJ07_LOGO` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL;
