
-- add token que o gateway retorna ao realizar a transacao
ALTER TABLE `PAG01_TRANSACAO` ADD `TOKEN_GATEWAY` VARCHAR(200) NULL AFTER `TRANSACAO_DT_CADASTRO`, ADD INDEX (`TOKEN_GATEWAY`);

-- add forma de pagamento no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_FORMA_PAG` VARCHAR(50) NULL DEFAULT NULL AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_FORMA_PAG`);

-- add o gateway escolhido no pedido
ALTER TABLE `LOJ11_PEDIDO` ADD `LOJ11_GATEWAY` VARCHAR(50) NOT NULL DEFAULT 'pagseguro' AFTER `LOJ11_USUARIO_ID`, ADD INDEX (`LOJ11_GATEWAY`);

-- permite produto null - para o caso de venda avulsa
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` CHANGE `LOJ12_PRODUTO_ID` `LOJ12_PRODUTO_ID` INT(11) NULL; 

-- novos campos do pedido
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` ADD `LOJ12_NOME_PRODUTO` VARCHAR(100) NOT NULL AFTER `LOJ12_PEDIDO_ID`, ADD `LOJ12_QTD` INT NOT NULL AFTER `LOJ12_NOME_PRODUTO`, ADD `LOJ12_VLR_UNID` DECIMAL(10,2) NOT NULL AFTER `LOJ12_QTD`, ADD `LOJ12_ID_VARIACAO` INT NOT NULL AFTER `LOJ12_VLR_UNID`;

-- exclusao do campo stats da tabela LOJ12_PRODUTO_PEDIDO 
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` DROP `LOJ12_STATS`;

-- a variação passa a ficar no pedido, ou seja um pedido tem uma variacao
DROP TABLE `LOJ13_PRODUTO_PEDIDO_VARIACAO`;

-- novo index para relacionamento
ALTER TABLE `LOJ12_PRODUTO_PEDIDO` ADD INDEX(`LOJ12_ID_VARIACAO`);

-- correção de tipo de campo
ALTER TABLE `LOJ07_LOJA` CHANGE `LOJ07_NOME` `LOJ07_NOME` VARCHAR(100) NOT NULL;
ALTER TABLE `LOJ09_VARIACAO_PRODUTO` CHANGE `LOJ09_GRUPO` `LOJ09_GRUPO` VARCHAR(50) NOT NULL;

-- o usuário (quem compra) pode nao ser cadastrado no sistema
ALTER TABLE `LOJ11_PEDIDO` CHANGE `LOJ11_USUARIO_ID` `LOJ11_USUARIO_ID` INT(11) NULL;

-- campo para identificar a hash do pagseguro da loja
ALTER TABLE `LOJ07_LOJA` ADD `LOJ07_HASH_PAGSEGURO` VARCHAR(100) NOT NULL AFTER `LOJ07_EMAIL`, ADD INDEX (`LOJ07_HASH_PAGSEGURO`);

-- Dados para teste
INSERT INTO `LOJ02_CLIENTE` (`LOJ02_ID`, `LOJ02_NOME`, `LOJ02_DESCRICAO`, `LOJ02_TELEFONE`, `LOJ02_CELULAR`, `LOJ02_STATUS`, `LOJ02_DT_INCLUSAO`, `LOJ02_CPF`, `LOJ02_CNPJ`) VALUES (NULL, 'CLIENTE - TESTE', 'De teste', '(31) 99999-9999', '', '1', CURRENT_TIMESTAMP, '822.238.708-13', '');
INSERT INTO `LOJ07_LOJA` (`LOJ07_ID`, `LOJ07_CLIENTE_ID`, `LOJ07_NOME`, `LOJ07_DESCRICAO`, `LOJ07_LOGO`, `LOJ07_TELEFONE`, `LOJ07_EMAIL`, `LOJ07_STATUS`, `LOJ07_DT_INCLUSAO`) VALUES (NULL, '1', 'Loja - TESTE', 'Descrição da Loja teste', NULL, NULL, 'eduardomatias.1989@gmail.com', '1', CURRENT_TIMESTAMP);
INSERT INTO `LOJ08_PRODUTO` (`LOJ08_ID`, `LOJ08_LOJA_ID`, `LOJ08_NOME`, `LOJ08_DESCRICAO`, `LOJ08_PRECO`, `LOJ08_QTD_VIEW`, `LOJ08_QTD_COMPART`, `LOJ08_STATUS`, `LOJ08_DT_INCLUSAO`) VALUES (NULL, '1', 'Produto Teste', 'De teste', '99.90', '0', '0', '1', CURRENT_TIMESTAMP);
INSERT INTO `LOJ09_VARIACAO_PRODUTO` (`LOJ09_ID`, `LOJ09_PRODUTO_ID`, `LOJ09_DESCRICAO`, `LOJ09_GRUPO`) VALUES (NULL, '1', 'PRETO', 'COR'), (NULL, '1', 'AZUL', 'COR');
INSERT INTO `LOJ11_PEDIDO` (`LOJ11_ID`, `LOJ11_CLIENTE_ID`, `LOJ11_USUARIO_ID`, `LOJ11_GATEWAY`, `LOJ11_FORMA_PAG`, `LOJ11_VALOR`, `LOJ11_NUM_PARCELA`, `LOJ11_STATUS`, `LOJ11_DT_INCLUSAO`) VALUES (NULL, '1', NULL, 'pagseguro', 'CreditCard', '99.90', '1', '1', CURRENT_TIMESTAMP);
INSERT INTO `LOJ12_PRODUTO_PEDIDO` (`LOJ12_ID`, `LOJ12_PRODUTO_ID`, `LOJ12_PEDIDO_ID`, `LOJ12_NOME_PRODUTO`, `LOJ12_QTD`, `LOJ12_VLR_UNID`, `LOJ12_ID_VARIACAO`) VALUES (NULL, '1', '3', 'Produto Teste', '1', '99.90', '1');